# Generated by Django 4.1.3 on 2022-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/tickets'),
        ),
    ]
