# Generated by Django 4.1.3 on 2023-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_train_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='time',
        ),
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
