# Generated by Django 4.1.3 on 2023-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_train_time_train_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
