# Generated by Django 4.1.3 on 2023-01-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_train_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='date',
            new_name='time',
        ),
    ]
