# Generated by Django 4.1.3 on 2023-01-15 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0006_alter_train_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='bookers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
