# Generated by Django 4.1.3 on 2023-01-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_train_bookers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
